import type { Metadata } from "next";
import "@/styles/globals.css";
import { RootClientLayout } from "@/components/RootClientLayout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <RootClientLayout children={children} />
            </body>
        </html>
    );
}
